## What are Tensors?

A tensor is a specialized multi-dimensional array designed for mathematical and computational efficiency.

---

## Real-World Examples of Tensors

### 1. Scalars (0-Dimensional Tensors)

A scalar represents a single value.

#### Example
- Loss value after a forward pass in a neural network.
- Temperature, probability, or accuracy score.

#### Examples of Scalars

```python
5.0
-3.14
```

---

### 2. Vectors (1-Dimensional Tensors)

A vector represents a sequence or collection of values.

#### Example
- Word embeddings in Natural Language Processing (NLP).

#### Example Vector

```python
[0.12, -0.84, 0.33]
```

This can represent a word embedding generated using models like Word2Vec or GloVe.

---

### 3. Matrices (2-Dimensional Tensors)

A matrix represents tabular or grid-like data.

#### Example
- Grayscale images

Each value represents pixel intensity.

#### Example Matrix

```python
[
 [0, 255, 128],
 [34, 90, 180]
]
```

---

### 4. 3D Tensors (Colored Images)

A 3D tensor adds another dimension, commonly used for image channels.

#### Example
- RGB Images

#### Shape Format

```python
[width, height, channels]
```

#### Example

```python
[256, 256, 3]
```

Where:
- `256 × 256` → Image size
- `3` → RGB channels

---

### 5. 4D Tensors (Batches of RGB Images)

A 4D tensor adds the batch dimension.

#### Example
- Batch of colored images

#### Shape Format

```python
[batch_size, width, height, channels]
```

#### Example

```python
[32, 128, 128, 3]
```

Where:
- `32` → Number of images
- `128 × 128` → Image size
- `3` → RGB channels

---

### 6. 5D Tensors (Video Data)

A 5D tensor adds a time/frame dimension.

#### Example
- Video clips

#### Shape Format

```python
[batch_size, frames, width, height, channels]
```

#### Example

```python
[10, 16, 64, 64, 3]
```

Where:
- `10` → Number of video clips
- `16` → Frames per video
- `64 × 64` → Frame size
- `3` → RGB channels

---

## Why Are Tensors Useful?

### 1. Mathematical Operations

Tensors support efficient mathematical computations such as:
- Addition
- Multiplication
- Dot Product
- Matrix Multiplication
- Broadcasting

These operations are essential for neural networks.

---

### 2. Representation of Real-World Data

Different types of data can be represented using tensors.

#### Examples
- Images → 3D tensors
- Text → 2D or 3D tensors
- Audio → 1D or 2D tensors
- Videos → 5D tensors

#### Text Representation

```python
[sequence_length, embedding_size]
```

---

### 3. Efficient Computations

Tensors are optimized for hardware acceleration using:
- GPUs
- TPUs

This enables faster training and inference in deep learning models.

---

## Where Are Tensors Used in Deep Learning?

### 1. Data Storage

Training data such as:
- Images
- Text
- Audio
- Videos

are stored as tensors.

---

### 2. Weights and Biases

The learnable parameters of neural networks are stored as tensors.

#### Examples
- Weight matrices
- Bias vectors

---

### 3. Matrix Operations

Deep learning relies heavily on tensor operations such as:
- Matrix multiplication
- Dot products
- Broadcasting

---

### 4. Training Process

#### Forward Pass
Input tensors flow through the neural network layers.

#### Backward Pass
Gradients are computed as tensors during backpropagation.

These gradients are used to update model parameters.

# Code

In [2]:
import torch
print(torch.__version__)

2.10.0+cpu


In [4]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using Gpu : {torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available")

GPU is not available


## Creating Tensors

In [6]:
# using empty
a = torch.empty(2,3)
a

tensor([[6.9843e-28, 0.0000e+00, 6.9883e-28],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [7]:
# check type
type(a)

torch.Tensor

In [8]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
# using rand
torch.rand(2,3)

tensor([[0.8197, 0.4913, 0.5803],
        [0.9256, 0.0053, 0.8843]])

In [12]:
# manual seed
torch.manual_seed(42) # for creating same tensors multiple time
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [13]:
# usnig tensors
torch.tensor([[1,2,3],[4,5,6]]) # for customized tensors

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))
print("-------------------------------------------------------------------------------------------------")
# using linspace
print("using linspace ->", torch.linspace(0,10,10))
print("-------------------------------------------------------------------------------------------------")

# using eye
print("using eye ->", torch.eye(5))
print("-------------------------------------------------------------------------------------------------")

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
-------------------------------------------------------------------------------------------------
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
-------------------------------------------------------------------------------------------------
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
-------------------------------------------------------------------------------------------------
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [16]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
x.shape

torch.Size([2, 3])

In [18]:
torch.empty_like(x) # for creating same shape tensor

tensor([[          318769024,           306892512, 4661726013461248228],
        [4681742012764214613,                  48,                  48]])

In [19]:
torch.zeros_like(x) # for creating same shape tensor but all zeros

tensor([[0, 0, 0],
        [0, 0, 0]])

In [20]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [21]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

## Tensor Data Types

In [22]:
# find data type
x.dtype

torch.int64

In [23]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [24]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

### 1. Scalar operation

In [27]:
x = torch.rand(2,2)
# addition
print(x + 2)
print()
# substraction
print(x - 2)
print()
# multiplication
print(x * 3)
print()
# division
print(x / 3)
print()
# int division
print((x * 100)//3)
print()
# mod
print(((x * 100)//3)%2)
print()
# power
print(x**2)

tensor([[2.8694, 2.5677],
        [2.7411, 2.4294]])

tensor([[-1.1306, -1.4323],
        [-1.2589, -1.5706]])

tensor([[2.6082, 1.7031],
        [2.2233, 1.2882]])

tensor([[0.2898, 0.1892],
        [0.2470, 0.1431]])

tensor([[28., 18.],
        [24., 14.]])

tensor([[0., 0.],
        [0., 0.]])

tensor([[0.7559, 0.3223],
        [0.5492, 0.1844]])


### 2. Element wise operation


In [28]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414]])
tensor([[0.2969, 0.8317, 0.1053],
        [0.2695, 0.3588, 0.1994]])


In [29]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.2916, 0.5739, 0.0560],
        [0.0885, 0.2696, 0.0426]])

In [30]:
c = torch.tensor([1, -2, 3, -4])

In [31]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [32]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [33]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [34]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [35]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [36]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [37]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [38]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[7., 9., 2.],
        [0., 5., 9.]])

In [39]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([18., 14.])

In [40]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([3.5000, 7.0000, 5.5000])

In [41]:
# median
torch.median(e)

tensor(5.)

In [42]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [43]:
# product
torch.prod(e)

tensor(0.)

In [44]:
# standard deviation
torch.std(e)

tensor(3.7238)

In [45]:
# variance
torch.var(e)

tensor(13.8667)

In [46]:
# argmax
torch.argmax(e)

tensor(1)

In [47]:
# argmin
torch.argmin(e)

tensor(3)

### 4. Matrix operations

In [48]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[3, 4, 9],
        [6, 2, 0]])
tensor([[6, 2],
        [7, 9],
        [7, 3]])


In [49]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[109,  69],
        [ 50,  30]])

In [50]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [51]:
# transpose
torch.transpose(f, 0, 1)

tensor([[3, 6],
        [4, 2],
        [9, 0]])

In [52]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[3., 4., 3.],
        [7., 0., 9.],
        [0., 9., 6.]])

In [53]:
  # determinant
torch.det(h)

tensor(-222.)

In [54]:
# inverse
torch.inverse(h)

tensor([[ 0.3649, -0.0135, -0.1622],
        [ 0.1892, -0.0811,  0.0270],
        [-0.2838,  0.1216,  0.1261]])

### 5. Comparison operations

In [55]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[9, 5, 4],
        [8, 8, 6]])
tensor([[0, 0, 0],
        [0, 1, 3]])


In [57]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j


tensor([[True, True, True],
        [True, True, True]])

### 6. Special functions

In [58]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[0., 1., 1.],
        [7., 9., 4.]])

In [59]:
# log
torch.log(k)

tensor([[  -inf, 0.0000, 0.0000],
        [1.9459, 2.1972, 1.3863]])

In [60]:
# exp
torch.exp(k)

tensor([[1.0000e+00, 2.7183e+00, 2.7183e+00],
        [1.0966e+03, 8.1031e+03, 5.4598e+01]])

In [61]:
# sqrt
torch.sqrt(k)

tensor([[0.0000, 1.0000, 1.0000],
        [2.6458, 3.0000, 2.0000]])

In [62]:
# sigmoid
torch.sigmoid(k)

tensor([[0.5000, 0.7311, 0.7311],
        [0.9991, 0.9999, 0.9820]])

In [63]:
# softmax
torch.softmax(k, dim=0)

tensor([[9.1105e-04, 3.3535e-04, 4.7426e-02],
        [9.9909e-01, 9.9966e-01, 9.5257e-01]])

In [64]:
# relu
torch.relu(k)

tensor([[0., 1., 1.],
        [7., 9., 4.]])

## Inplace Operations

In [65]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.0874, 0.0041, 0.1088],
        [0.1637, 0.7025, 0.6790]])
tensor([[0.9155, 0.2418, 0.1591],
        [0.7653, 0.2979, 0.8035]])


In [67]:
m.add_(n) # by this we can add n in m , inplace of m , not creating new tensors after addition

tensor([[1.9183, 0.4876, 0.4271],
        [1.6942, 1.2983, 2.2860]])

In [68]:
# we can use this inplace operation for any function in pytorch just add '_' infront of function

# Tensors Operation on GPU

In [2]:
import torch
# check if GPU is available
torch.cuda.is_available()

True

In [6]:
# set device
device = torch.device('cuda')

# creating a new tensor on GPU
tensor_gpu = torch.rand((2, 3), device=device)

print(f'Tensor on gpu :  {tensor_gpu}')
print()

# moving an existing tensor to GPU
tensor_cpu = torch.rand((2, 3))
tensor_gpu = tensor_cpu.to(device)

print(tensor_gpu)

Tensor on gpu :  tensor([[0.0602, 0.5944, 0.6345],
        [0.4106, 0.2982, 0.6854]], device='cuda:0')

tensor([[0.2027, 0.1474, 0.0506],
        [0.0743, 0.5251, 0.6619]], device='cuda:0')


# Comparison GPU vs CPU

In [7]:
import torch
import time

# Define the size of the matrices
size = 10000  # Large size for performance comparison

# Create random matrices on CPU
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

# Measure time on CPU
start_time = time.time()

result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)  # Matrix multiplication on CPU

cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")

# Move matrices to GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

# Measure time on GPU
start_time = time.time()

result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)  # Matrix multiplication on GPU

torch.cuda.synchronize()  # Ensure all GPU operations are complete

gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time:.4f} seconds")

Time on CPU: 16.6958 seconds
Time on GPU: 0.6852 seconds


# Reshaping Tensors

In [10]:
# Create a tensor
a = torch.ones(4, 4)

print(a)

# Reshape tensor
reshaped_tensor = a.reshape(2, 2, 2, 2)

print("\nReshaped Tensor:")
print(reshaped_tensor)

# Flatten tensor
flattened_tensor = a.flatten() # convert in one dimension

print("\nFlattened Tensor:")
print(flattened_tensor)


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Reshaped Tensor:
tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

Flattened Tensor:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


In [11]:
# Create a random tensor with shape (2, 3, 4)
b = torch.rand(2, 3, 4)

print("Original Tensor:")
print(b)

# permute changes the order of dimensions
permuted_tensor = b.permute(2, 1, 0)

print("\nPermuted Tensor Shape:")
print(permuted_tensor.shape)

# unsqueeze adds a new dimension at the specified position
c = torch.rand(226, 226, 3)

unsqueezed_tensor = c.unsqueeze(0)

print("\nUnsqueezed Tensor Shape:")
print(unsqueezed_tensor.shape)

# squeeze removes dimensions with size 1
d = torch.rand(1, 20)

squeezed_tensor = d.squeeze()

print("\nSqueezed Tensor Shape:")
print(squeezed_tensor.shape)

Original Tensor:
tensor([[[0.0114, 0.0898, 0.8822, 0.2984],
         [0.6788, 0.6037, 0.5384, 0.7446],
         [0.3702, 0.4549, 0.2657, 0.6965]],

        [[0.4953, 0.6672, 0.1874, 0.4222],
         [0.2601, 0.2683, 0.7438, 0.4492],
         [0.9945, 0.0742, 0.0390, 0.3284]]])

Permuted Tensor Shape:
torch.Size([4, 3, 2])

Unsqueezed Tensor Shape:
torch.Size([1, 226, 226, 3])

Squeezed Tensor Shape:
torch.Size([20])


# NumPy and PyTorch

In [12]:
import torch
import numpy as np

# Create a PyTorch tensor
a = torch.tensor([1, 2, 3])

print("PyTorch Tensor:")
print(a)

# Convert PyTorch tensor to NumPy array
# numpy() converts tensor into NumPy array
b = a.numpy()

print("\nConverted to NumPy Array:")
print(b)

# Create a NumPy array
c = np.array([4, 5, 6])

print("\nNumPy Array:")
print(c)

# Convert NumPy array to PyTorch tensor
# from_numpy() converts NumPy array into PyTorch tensor
d = torch.from_numpy(c)

print("\nConverted to PyTorch Tensor:")
print(d)

PyTorch Tensor:
tensor([1, 2, 3])

Converted to NumPy Array:
[1 2 3]

NumPy Array:
[4 5 6]

Converted to PyTorch Tensor:
tensor([4, 5, 6])
